name: Image push on docker registry

on:
  push:
    branches:
      - develop

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_REPOSITORY: recovery.back
  VERSION: "25"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: 1️⃣ 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 2️⃣ Build
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.VERSION }}
          cache: gradle

      - name: 3️⃣ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 4️⃣ Gradlew build
        run: ./gradlew clean build

      - name: 5️⃣ Get current time
        uses: josStorer/get-current-time@v2.1.2
        id: current_time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: 6️⃣ Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 7️⃣ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 8️⃣ Build and push image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ github.ref_name }}-${{ steps.current_time.outputs.formattedTime }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ github.ref_name }}-latest
          push: true
